/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StringOperations;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

class StringOperationsTest {
    private StringOperations stringOperations;


    @BeforeEach
    void setUp() {
        stringOperations = new StringOperations();

    }

    @AfterEach
    void tearDown() {
        stringOperations = null;
    }



    @Test
    void concatTwoEmpty(){
        String inputA = "";
        String inputB = "";
        assertEquals("" ,stringOperations.concat(inputA,inputB));
    }

    @Test
    void concatNonEmptyWords(){
        String inputA = "kotek";
        String inputB = "piesek";
        assertEquals("kotekpiesek" ,stringOperations.concat(inputA,inputB));
    }

    @Test
    void concatSameLetters(){
        String inputA = "ab";
        String inputB = "ba";
        assertEquals("abba" ,stringOperations.concat(inputA,inputB));
    }

    @Test
    void palindromeEmpty(){
        String input = "";
        assertTrue(stringOperations.isPalindrome(input));
    }

}
